kind: pipeline
name: gcc/amd64/linux

platform:
  arch: amd64

steps:
- name: build
  image: gcc
  pull: true
  commands:
  - ./tools/ci-build.sh --cores=4
  - make check

---
kind: pipeline
name: gcc/arm64/linux

platform:
  arch: arm64

steps:
- name: build
  image: gcc
  pull: true
  commands:
  - export CFLAGS="-DITERATE=400 -DPAIRS_S=100 -DITERATIONS=24"
  - ./tools/ci-build.sh --cores=4
  - make check
